---
title: "Import "Junção" Database"
author: "James Hunter"
date: "August 22, 2015"
output: html_document
---

Load Libraries
--------------
```{r libs}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(DescTools))
```

In Excel, tranlate Plan2 to a csv file as XLConnect can't build a large enough Java heap. Then read it in. 

Read in Plan 2
--------------
```{r load}
# plan2 <- read.csv("juncao_plan2.csv")

## convert plan2 to dplyr data_frames
# plan2 <- as_data_frame(plan2)

```

Set up Class Resistances based on Anderson's Dictionary
Using Stanford Definitions
-------------------------------------------------------

```{r reducedbase}
# Run only once; then use saved version
#classres <- data_frame(code = as.character(plan2$code),
#                       ano = plan2$ano,
#                       subtype = plan2$subtipo,
#                       NNRTI = plan2$NNRTI_Stanford,
#                       NRTI = plan2$NRTI_Stanford,
#                       PI = plan2$PI_Stanford)
#classres <- mutate(classres, numclasses = (NNRTI > 0) + 
#      (NRTI > 0) + (PI > 0))
#classres <- mutate(classres, oneclass = numclasses == 1)
#classres <- mutate(classres, twoclass = numclasses == 2)
#classres <- mutate(classres, threeclass = numclasses == 3)
#save(plan2, classres, file = "juncao_data.RData")
``` 

Analysis and Visualization of Results from this Data Frame
----------------------------------------------------------

```{r descriptive}
load("juncao_data.RData")
table(classres$subtype, classres$numclasses)
table(classres$subtype, classres$ano)
table(classres$numclasses, classres$ano)
table(classres$ano)
```


